/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BreedsBreedNameImport } from './routes/breeds/$breedName'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BreedsBreedNameRoute = BreedsBreedNameImport.update({
  path: '/breeds/$breedName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/breeds/$breedName': {
      id: '/breeds/$breedName'
      path: '/breeds/$breedName'
      fullPath: '/breeds/$breedName'
      preLoaderRoute: typeof BreedsBreedNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  BreedsBreedNameRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/breeds/$breedName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/breeds/$breedName": {
      "filePath": "breeds/$breedName.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
